service: ${env:BUILD_PROJECT}-github-webhook

plugins:
  - serverless-step-functions
  - serverless-parameters
  - serverless-portable-templates
  - serverless-pseudo-parameters

custom:
  parameters:
    GithubUsername:
      Type: String
      Default: ${env:GITHUB_USERNAME}
      Description: Github username, this is the user which will be displayed
    GithubRepository:
      Type: String
      Default: ${env:GITHUB_REPOSITORY}
      Description: "Github repository url, eg: https://github.com/[username]/[repository]"
    GithubAccessToken:
      Type: String
      Default: ${env:GITHUB_ACCESS_TOKEN}
      Description: Your generated github access token
      NoEcho: true
    CodebuildProject:
      Type: String
      Default: ${env:BUILD_PROJECT}
      Description: Name of the build project that should be triggered

provider:
  name: aws
  runtime: nodejs6.10
  stage: trigger
  versionFunctions: false

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - codebuild:*
      Resource: "arn:aws:codebuild:#{AWS::Region}:#{AWS::AccountId}:project/${env:BUILD_PROJECT}"

  environment:
    BUILD_PROJECT:
      Ref: CodebuildProject
    GITHUB_USERNAME:
      Ref: GithubUsername
    GITHUB_ACCESS_TOKEN:
      Ref: GithubAccessToken
    GITHUB_REPOSITORY:
      Ref: GithubRepository

functions:
  start-build:
    handler: handler.start_build

  check-build-status:
    handler: handler.check_build_status

  build-done:
    handler: handler.build_done

  webhook-resource:
    handler: webhook.resource

resources:
  Resources:
    GithubWebhook:
      Type: Custom::GithubWebhook
      Properties:
        ServiceToken:
          Fn::GetAtt:
            - WebhookDashresourceLambdaFunction
            - Arn
        Endpoint:
          Fn::Join:
            - ""
            -
              - https://
              - Ref: "ApiGatewayRestApi"
              - .execute-api.${opt:region, self:provider.region}.amazonaws.com/${opt:stage, self:provider.stage}/trigger-build/

  Outputs:
    TriggerEndpoint:
      Value:
        Fn::Join:
          - ""
          -
            - https://
            - Ref: "ApiGatewayRestApi"
            - .execute-api.${opt:region, self:provider.region}.amazonaws.com/${opt:stage, self:provider.stage}/trigger-build/

stepFunctions:
  stateMachines:
    build-for-commit:
      events:
        - http:
            path: trigger-build
            method: POST
      definition:
        Comment: "Check for build status for the given build project, and mark it when done on GH"
        StartAt: start_build
        States:
          start_build:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-${opt:stage}-start-build"
            Next: check_build_status
          wait_a_bit:
            Type: Wait
            Seconds: 5
            Next: check_build_status
          check_build_status:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-${opt:stage}-check-build-status"
            Next: check_build_status_outcome
          check_build_status_outcome:
            Type: Choice
            Choices:
            - Variable: "$.buildComplete"
              BooleanEquals: true
              Next: build_done
            Default: wait_a_bit
          build_done:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:#{AWS::StackName}-${opt:stage}-build-done"
            End: true
